import os
import json
from datetime import datetime, timezone
import numpy as np
import xarray as xr

# Grid constants to ensure correct coordinates
LATS = [round(5.0 + i * 0.25, 2) for i in range(101)]
LONS = [round(45.0 + i * 0.25, 2) for i in range(241)]
DEPTHS_M = [0, 5, 10, 20, 30, 50, 75, 100, 125, 150, 200, 300, 500, 700, 1000]

def save_model_output(pred: np.ndarray, day: str, out_dir: str = "data/model_output",
                      model_version: str = "oceanembed-gnn-oam-v1"):
    """
    pred: numpy array (15, 101, 241) in degC, depth order
    0..1000 m, lat 5->30 ascending, lon 45->105 ascending,
    NaN on land. day: 'YYYY-MM-DD'.
    Writes thetao_<day>.nc (CF format) and thetao_<day>.json.
    
    Full grid required. If the model predicts one profile per target cell, 
    the team must loop over all ocean cells for that date and assemble 
    the results into the (15, 101, 241) array before calling this function.
    """
    os.makedirs(out_dir, exist_ok=True)
    
    datetime.strptime(day, "%Y-%m-%d")  # raises on a malformed date
    if pred.shape != (15, 101, 241):
        raise ValueError(f"pred array must have shape (15, 101, 241), got {pred.shape}")
        
    ds = xr.Dataset(
        {
            "thetao": (["depth", "lat", "lon"], pred.astype(np.float32), {
                "units": "degree_Celsius",
                "standard_name": "sea_water_potential_temperature",
                "long_name": "Reconstructed sea water potential temperature",
            })
        },
        coords={
            "depth": ("depth", DEPTHS_M, {"units": "m", "positive": "down", "axis": "Z"}),
            "lat": ("lat", LATS, {"units": "degrees_north", "axis": "Y"}),
            "lon": ("lon", LONS, {"units": "degrees_east", "axis": "X"}),
        }
    )
    
    # Add a single time step (the product date) for CF compliance
    ds = ds.expand_dims({"time": [np.datetime64(day, "ns")]})
    ds["time"].attrs = {"standard_name": "time", "axis": "T"}
    ds.attrs = {
        "Conventions": "CF-1.8",
        "title": "OceanEmbed subsurface temperature reconstruction",
        "model_version": model_version,
    }

    nc_path = os.path.join(out_dir, f"thetao_{day}.nc")
    encoding = {
        "thetao": {
            "_FillValue": np.float32(np.nan),
            "zlib": True,
            "complevel": 4
        },
        "time": {"units": "days since 1970-01-01 00:00:00", "calendar": "standard"},
    }
    ds.to_netcdf(nc_path, encoding=encoding, engine="netcdf4")
    
    # Write metadata sidecar
    json_path = os.path.join(out_dir, f"thetao_{day}.json")
    meta = {
        "model_version": model_version,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "notes": "Generated by save_model_output script"
    }
    with open(json_path, "w") as f:
        json.dump(meta, f, indent=2)
        
    print(f"Saved {nc_path} and {json_path}")
